# Generated by Django 6.0.2 on 2026-02-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGood', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStock', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Goodmoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.goods')),
                ('stockFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_from', to='StockApp.stocks')),
                ('stockTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_to', to='StockApp.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Goodincomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.goods')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.stocks')),
            ],
        ),
    ]
