# Generated by Django 6.0.2 on 2026-02-20 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodincomes',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goodmoves',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
