# Generated by Django 6.0.2 on 2026-03-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0002_registrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.FloatField(default=0.0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.goods')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.stocks')),
            ],
        ),
    ]
